---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Add GPG Key
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /etc/apt/keyrings/nodesource.asc

- name: Add NodeJS apt sources file
  ansible.builtin.template:
    src: nodesource.list.j2
    dest: /etc/apt/sources.list.d/nodesource.list

- name: Install Node
  ansible.builtin.apt:
    update_cache: true
    name: nodejs

- name: Install npm globals
  # https://docs.ansible.com/ansible/latest/collections/community/general/npm_module.html
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: present
  with_items: "{{ npm_globals }}"